### ISSUE TITLE
runbook on docker fresh install - many operations cause a stathat.StatHatError stack trace

### ISSUE THREAD

**Issue by scumola** [Runbook/runbook#419]
Docker fresh install just as documented on Ubuntu 16.04.

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/src/web/reaction/views.py", line 127, in addreaction_page
    app.config['ENVNAME'] + ' Reaction Added', 1)
  File "/src/web/stathat.py", line 171, in ez_count
    return stats.count(count, async=async)
  File "/src/web/stathat.py", line 79, in count
    return self._send(self.COUNT_PATH, {'count': count}, async=async)
  File "/src/web/stathat.py", line 113, in _send
    raise StatHatError('Something bad happened: %s' % raw)
StatHatError: Something bad happened:

This happens when creating a new Email Notification Action, when creating a new HTTP GET monitor and many other actions.  Is something missing from the docker containers or perhaps some package is now incompatible in some way?  Is this being maintained?

**Comment by scumola** [comment]
When this happens, the runbook docker container dies at the same time.

**Comment by madflojo** [comment]
Looks like the external calls to [Stathat](https://www.stathat.com/) are failing and returning that error. When I get some time I can take a look at revising it to not call out to stathat if there is not a valid URL. 

Also, tbh I'm not really actively maintaining Runbook these days, I have more moved my attention to [Automatron](https://github.com/madflojo/automatron) which is similar to Runbook but a bit different.
